### PR TITLE
propose fix for collapse vaccine function addition

### LINKED ISSUE #146: Create a function for conditional actions that rely on `collapse_vaccine=True`
Issue:
Beginning at lines 92 and 143, we have 2 very similar chunks of 20+ lines for what to do when `collapse_vaccine=True`. There's not a lot of domain expertise in this function, so I don't really know what we're doing there beyond "combine vaccine variables for more intuitive comparisons"

Acceptance conditions:
Create a descriptive and documented function that can be reused at line 92 and line 143. Please try to have the function not exceed 15 lines of code, so it may be necessary to have sub functions for this.

### PR DESCRIPTION
**Pull request by lpw3**
This takes the `collapse_vaccine` boolean argument and creates a function flexible to use with `all_dates == T` or `all_dates == F`. Should be compared and combined with issue 147 that does a similar change to create `state_df` flexibly considering the `all_dates` arg.

### CODE REVIEW

File: R/calc_aggregate_counts.R [hunk 1]
```diff
@@ -29,6 +29,28 @@
...
+sub_vax_data <- function(df, ad){
+  grp_vars <- if(ad) c('State', 'Date') else c('State')
+  arrange_vars <- if(ad) c('State', 'Date', 'Measure') else c('State', 'Measure')
+  res <- df %>%
+    group_by_at(grp_vars) %>%
+    mutate(No.Initiated = !("Residents.Initiated" %in% Measure)) %>%
+    filter(No.Initiated ) %>%
+    filter(Measure %in% c("Residents.Completed")) %>%
+    arrange_at(arrange_vars) %>%
+    filter(1:n() == 1) %>% #if there are duplicates, take the highest one
```
Comment (hjohns12) [inline R/calc_aggregate_counts.R:41]: Sorry for being slow, but what is this filtering duplicates of?

**Review by hjohns12 — APPROVED** [review]
This works locally for me, thank you for doing it!

I noticed that when all_dates = F and collapse_vaccine = T, these are the only rows that get changed. Just a comment so folks are aware

Screen Shot 2022-03-18 at 11 51 31
!

File: R/calc_aggregate_counts.R (hunk 1 above)
Comment (ssciolist) [reply R/calc_aggregate_counts.R:41]: The way I read this, I think it would filter any out any overall duplicated rows (`1:n()`is not equal to 1) so that we only take one `Residents.Completed` value and transpose it onto a new `Residents.Initiated`. I don't see how this would necessarily take the 'highest' value though, or how a value would be highest in the event that we have a purely duplicated row. Maybe @lpw3 can answer that?

In my review, I couldn't find any scenario where there were actually duplicated rows. So one could argue that we should remove this line for clarity. I'd prefer to assume that it was added for some reason, and filtering out duplicates pro-actively is a good idea even if we don't need to.

File: R/calc_aggregate_counts.R [hunk 2]
```diff
@@ -29,6 +29,28 @@
 #' calc_aggregate_counts(state = TRUE, all_dates = TRUE)
 #' @export
 
+sub_vax_data <- function(df, ad){
```
Comment (ssciolist) [inline R/calc_aggregate_counts.R:32]: At first, I didn't know what `ad` was. Since we're using `all_dates` in other places, I'd prefer this function argument to be changed to `all_dates` to maintain consistency.

File: R/calc_aggregate_counts.R [hunk 3]
```diff
@@ -13,8 +13,8 @@
 #' if all_dates is FALSE for all variables EXCEPT .Confirmed and .Deaths
 #' @param ucla_only logical, only consider data from UCLA
 #' @param state logical, return state level data
-#' @param collapse_vaccine logical, combine vaccine variables for more
-#' intuitive comparisons
+#' @param collapse_vaccine logical, add variable for Residents.Initiated, equal to Residents.Completed,
```
Comment (ssciolist) [inline R/calc_aggregate_counts.R:16]: What you've done here is super useful, thank you. It's made me realized that I don't think `collapse_vaccine` is an intuitive name for this parameter -- maybe `sub_vax_data` for consistency with the new function you've created? I know that introducing this change would mean we'd need to make other downstream changes where this function is called, so I'm curious to hear your thoughts on that idea.

File: R/calc_aggregate_counts.R (hunk 2 above)
Comment (ssciolist) [reply R/calc_aggregate_counts.R:32]: Separately... I'm going to ask you to the same 2 things I asked Hope:
1. I'd like this new function to come after calc_aggregate_counts. My logic here is that you should be able to read through the main function first, then dig into supplementary functions as needed/if you care.
 2. I'd like to use the [naming convention that Google uses](https://google.github.io/styleguide/Rguide.html) for a private/helper function, which is starting the name of the function with a `.`. I like the way this delineates a core function from a helper function.

**Review by ssciolist — CHANGES_REQUESTED** [review]
Some changes requested. I loooove how you updated the documentation for this function to be clearer, very cool.

File: R/calc_aggregate_counts.R (hunk 1 above)
Comment (lpw3) [reply R/calc_aggregate_counts.R:41]: Yes, thanks Megan, that's correct! It arranges it by the highest value using the `arrange_at` function in the line above. I also didn't see any duplicate rows, but left it in in case there was some edge case that was added in for.

File: R/calc_aggregate_counts.R (hunk 3 above)
Comment (lpw3) [reply R/calc_aggregate_counts.R:16]: This is a good point. I did a search of the `covid19_behind_bars_scrapers` repo and there are no instances of `calc_aggregate_counts` being called with an argument specified for `collapse_vaccine`, so I will go ahead and change this.
